In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.3251,  2.1380, -0.0462], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([1.6749, 4.1380, 1.9538], grad_fn=<AddBackward0>)


In [4]:
z = y * y * 2
print(z)

tensor([ 5.6107, 34.2455,  7.6349], grad_fn=<MulBackward0>)


In [5]:
z = z.mean()
print(z)

tensor(15.8304, grad_fn=<MeanBackward0>)


In [6]:
z.backward()
print(x.grad)

tensor([2.2332, 5.5173, 2.6051])


In [7]:
z1 = y * y * 2
print(z1)

tensor([ 5.6107, 34.2455,  7.6349], grad_fn=<MulBackward0>)


In [8]:
z1.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [ ]:
v = torch.tensor([1, 0.1, 0.01], dtype=torch.float32)
print(v)

In [ ]:
z1.backward(v)

In [ ]:
print(x.grad)

In [ ]:
print(x)
x.requires_grad_(False)
print(x)

In [ ]:
x.requires_grad_(True)
print(x)
y = x.detach()
print(y)

In [ ]:
with torch.no_grad():
    y = x + 2
    print(x)
    print(y)

In [ ]:
weights = torch.ones(4, requires_grad=True)
print(weights)

In [ ]:
for epoch in range(3):
    model_output = (weights*5).sum()
    model_output.backward()
    print(weights.grad)

In [ ]:
for epoch in range(3):
    model_output = (weights*5).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    print(weights.grad)


### Backpropagation

In [ ]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
print(x)
print(y)

In [ ]:
w = torch.tensor(1.0, requires_grad=True)
print(w)

In [ ]:
y_hat = w * x
loss = (y_hat - y) ** 2
print(y_hat)
print(loss)

In [ ]:
loss.backward()

In [ ]:
print(w.grad)