In [17]:
import torch

In [18]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)
print(X)
print(y)

tensor([1., 2., 3., 4.])
tensor([2., 4., 6., 8.])


In [19]:
# model prediction
def forward(x):
    return w * x

In [20]:
# loss function
def loss(y, y_pred):
    return  ((y - y_pred)**2).mean()

In [21]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
alpha = 0.01
iterations = 50
print(w, alpha, iterations)

tensor(0., requires_grad=True) 0.01 50


In [22]:
print(forward(5))

for _ in range(iterations):
    # predict
    y_pred = forward(X)

    # calculate loss
    l = loss(y, y_pred)

    # gradient descent => backward pass in pytorch
    l.backward()

    # update weights
    with torch.no_grad():
        w -= alpha * w.grad

    # reset gradients
    w.grad.zero_()
    print(f"{_}, w: {w:.3f}, loss: {l:5f}")

print(forward(5))

tensor(0., grad_fn=<MulBackward0>)
0, w: 0.300, loss: 30.000000
1, w: 0.555, loss: 21.674999
2, w: 0.772, loss: 15.660188
3, w: 0.956, loss: 11.314487
4, w: 1.113, loss: 8.174717
5, w: 1.246, loss: 5.906232
6, w: 1.359, loss: 4.267253
7, w: 1.455, loss: 3.083090
8, w: 1.537, loss: 2.227532
9, w: 1.606, loss: 1.609392
10, w: 1.665, loss: 1.162786
11, w: 1.716, loss: 0.840112
12, w: 1.758, loss: 0.606981
13, w: 1.794, loss: 0.438544
14, w: 1.825, loss: 0.316848
15, w: 1.851, loss: 0.228923
16, w: 1.874, loss: 0.165397
17, w: 1.893, loss: 0.119499
18, w: 1.909, loss: 0.086338
19, w: 1.922, loss: 0.062379
20, w: 1.934, loss: 0.045069
21, w: 1.944, loss: 0.032562
22, w: 1.952, loss: 0.023526
23, w: 1.960, loss: 0.016998
24, w: 1.966, loss: 0.012281
25, w: 1.971, loss: 0.008873
26, w: 1.975, loss: 0.006411
27, w: 1.979, loss: 0.004632
28, w: 1.982, loss: 0.003346
29, w: 1.985, loss: 0.002418
30, w: 1.987, loss: 0.001747
31, w: 1.989, loss: 0.001262
32, w: 1.991, loss: 0.000912
33, w: 1.992, 

## Gradient Descent using PyTorch Neural Network Module

### Type 1: Use optimizer for loss function

In [23]:
import torch.nn as nn

In [24]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)
print(X)
print(y)

tensor([1., 2., 3., 4.])
tensor([2., 4., 6., 8.])


In [25]:
# model prediction
def forward(x):
    return w * x

In [26]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
alpha = 0.01
iterations = 50
loss = nn.MSELoss()
optimizer = torch.optim.SGD([w], lr=alpha)
print(w, alpha, iterations)
print(loss, optimizer)

tensor(0., requires_grad=True) 0.01 50
MSELoss() SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [27]:
print(forward(5))

for _ in range(iterations):
    # predict
    y_pred = forward(X)

    # calculate loss
    l = loss(y, y_pred)

    # gradient descent => backward pass in pytorch
    l.backward()

    # update weights
    optimizer.step()

    # reset gradients
    w.grad.zero_()
    print(f"{_}, w: {w:.3f}, loss: {l:5f}")

print(forward(5))

tensor(0., grad_fn=<MulBackward0>)
0, w: 0.300, loss: 30.000000
1, w: 0.555, loss: 21.674999
2, w: 0.772, loss: 15.660188
3, w: 0.956, loss: 11.314487
4, w: 1.113, loss: 8.174717
5, w: 1.246, loss: 5.906232
6, w: 1.359, loss: 4.267253
7, w: 1.455, loss: 3.083090
8, w: 1.537, loss: 2.227532
9, w: 1.606, loss: 1.609392
10, w: 1.665, loss: 1.162786
11, w: 1.716, loss: 0.840112
12, w: 1.758, loss: 0.606981
13, w: 1.794, loss: 0.438544
14, w: 1.825, loss: 0.316848
15, w: 1.851, loss: 0.228923
16, w: 1.874, loss: 0.165397
17, w: 1.893, loss: 0.119499
18, w: 1.909, loss: 0.086338
19, w: 1.922, loss: 0.062379
20, w: 1.934, loss: 0.045069
21, w: 1.944, loss: 0.032562
22, w: 1.952, loss: 0.023526
23, w: 1.960, loss: 0.016998
24, w: 1.966, loss: 0.012281
25, w: 1.971, loss: 0.008873
26, w: 1.975, loss: 0.006411
27, w: 1.979, loss: 0.004632
28, w: 1.982, loss: 0.003346
29, w: 1.985, loss: 0.002418
30, w: 1.987, loss: 0.001747
31, w: 1.989, loss: 0.001262
32, w: 1.991, loss: 0.000912
33, w: 1.992, 

### Type 2: Use PyTorch Neural Networks Module for model training

In [33]:
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

n_samples, n_features = X.shape

print(X, X.shape)
print(y)

tensor([[1.],
        [2.],
        [3.],
        [4.]]) torch.Size([4, 1])
tensor([[2.],
        [4.],
        [6.],
        [8.]])


In [29]:
X_test = torch.tensor([5], dtype=torch.float32)
print(X_test, X_test.shape)

tensor([5.]) torch.Size([1])


In [30]:
input_size, output_size = n_features, n_features
model = nn.Linear(input_size, output_size)

In [31]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
alpha = 0.01
iterations = 100
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=alpha)
print(w, alpha, iterations)
print(loss, optimizer)

tensor(0., requires_grad=True) 0.01 100
MSELoss() SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [32]:
print(model(X_test).item())

for _ in range(iterations):
    # predict
    y_pred = model(X)

    # calculate loss
    l = loss(y, y_pred)

    # gradient descent => backward pass in pytorch
    l.backward()

    # update weights
    optimizer.step()

    [w, b] = model.parameters()
    print(f"{_}, w: {w[0][0].item():.3f}, loss: {l:5f}")

print(model(X_test).item())

2.5552608966827393
0, w: 0.840, loss: 18.124456
1, w: 1.267, loss: 12.576178
2, w: 1.817, loss: 5.031259
3, w: 2.397, loss: 0.319455
4, w: 2.912, loss: 1.456946
5, w: 3.274, loss: 7.715586
6, w: 3.424, loss: 15.089011
7, w: 3.337, loss: 18.857248
8, w: 3.026, loss: 16.608120
9, w: 2.544, loss: 9.781373
10, w: 1.972, loss: 2.747030
11, w: 1.405, loss: 0.008011
12, w: 0.937, loss: 3.317653
13, w: 0.647, loss: 10.557344
14, w: 0.583, loss: 17.092716
15, w: 0.756, loss: 18.740261
16, w: 1.137, loss: 14.445328
17, w: 1.662, loss: 6.957249
18, w: 2.244, loss: 1.069390
19, w: 2.785, loss: 0.550769
20, w: 3.195, loss: 5.733370
21, w: 3.406, loss: 13.299642
22, w: 3.382, loss: 18.406155
23, w: 3.127, loss: 17.784061
24, w: 2.684, loss: 11.831589
25, w: 2.127, loss: 4.359107
26, w: 1.549, loss: 0.150005
27, w: 1.046, loss: 1.898667
28, w: 0.702, loss: 8.485716
29, w: 0.575, loss: 15.694564
30, w: 0.686, loss: 18.910585
31, w: 1.017, loss: 16.075100
32, w: 1.511, loss: 9.003195
33, w: 2.087, loss