In [7]:
import torch

In [8]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)
print(X)
print(y)

tensor([1., 2., 3., 4.])
tensor([2., 4., 6., 8.])


In [9]:
# model prediction
def forward(x):
    return w * x

In [10]:
# loss function
def loss(y, y_pred):
    return  ((y - y_pred)**2).mean()

In [11]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
alpha = 0.01
iterations = 50
print(w, alpha, iterations)

tensor(0., requires_grad=True) 0.01 50


In [12]:
print(forward(5))

for epoch in range(iterations):
    # predict
    y_pred = forward(X)

    # calculate loss
    l = loss(y, y_pred)

    # gradient descent => backward pass in pytorch
    l.backward()

    # update weights
    with torch.no_grad():
        w -= alpha * w.grad

    # reset gradients
    w.grad.zero_()
    print(f"epoch {epoch}, w: {w:.3f}, loss: {l:5f}")

print(forward(5))

tensor(0., grad_fn=<MulBackward0>)
epoch 0, w: 0.300, loss: 30.000000
epoch 1, w: 0.555, loss: 21.674999
epoch 2, w: 0.772, loss: 15.660188
epoch 3, w: 0.956, loss: 11.314487
epoch 4, w: 1.113, loss: 8.174717
epoch 5, w: 1.246, loss: 5.906232
epoch 6, w: 1.359, loss: 4.267253
epoch 7, w: 1.455, loss: 3.083090
epoch 8, w: 1.537, loss: 2.227532
epoch 9, w: 1.606, loss: 1.609392
epoch 10, w: 1.665, loss: 1.162786
epoch 11, w: 1.716, loss: 0.840112
epoch 12, w: 1.758, loss: 0.606981
epoch 13, w: 1.794, loss: 0.438544
epoch 14, w: 1.825, loss: 0.316848
epoch 15, w: 1.851, loss: 0.228923
epoch 16, w: 1.874, loss: 0.165397
epoch 17, w: 1.893, loss: 0.119499
epoch 18, w: 1.909, loss: 0.086338
epoch 19, w: 1.922, loss: 0.062379
epoch 20, w: 1.934, loss: 0.045069
epoch 21, w: 1.944, loss: 0.032562
epoch 22, w: 1.952, loss: 0.023526
epoch 23, w: 1.960, loss: 0.016998
epoch 24, w: 1.966, loss: 0.012281
epoch 25, w: 1.971, loss: 0.008873
epoch 26, w: 1.975, loss: 0.006411
epoch 27, w: 1.979, loss: 

## Gradient Descent using PyTorch Neural Network Module

### Type 1: Use optimizer for loss function

In [13]:
import torch.nn as nn

In [14]:
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)
print(X)
print(y)

tensor([1., 2., 3., 4.])
tensor([2., 4., 6., 8.])


In [15]:
# model prediction
def forward(x):
    return w * x

In [16]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
alpha = 0.01
iterations = 50
loss = nn.MSELoss()
optimizer = torch.optim.SGD([w], lr=alpha)
print(w, alpha, iterations)
print(loss, optimizer)

tensor(0., requires_grad=True) 0.01 50
MSELoss() SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [17]:
print(forward(5))

for epoch in range(iterations):
    # predict
    y_pred = forward(X)

    # calculate loss
    l = loss(y, y_pred)

    # gradient descent => backward pass in pytorch
    l.backward()

    # update weights
    optimizer.step()

    # reset gradients
    w.grad.zero_()
    print(f"epoch {epoch}, w: {w:.3f}, loss: {l:5f}")

print(forward(5))

tensor(0., grad_fn=<MulBackward0>)
epoch 0, w: 0.300, loss: 30.000000
epoch 1, w: 0.555, loss: 21.674999
epoch 2, w: 0.772, loss: 15.660188
epoch 3, w: 0.956, loss: 11.314487
epoch 4, w: 1.113, loss: 8.174717
epoch 5, w: 1.246, loss: 5.906232
epoch 6, w: 1.359, loss: 4.267253
epoch 7, w: 1.455, loss: 3.083090
epoch 8, w: 1.537, loss: 2.227532
epoch 9, w: 1.606, loss: 1.609392
epoch 10, w: 1.665, loss: 1.162786
epoch 11, w: 1.716, loss: 0.840112
epoch 12, w: 1.758, loss: 0.606981
epoch 13, w: 1.794, loss: 0.438544
epoch 14, w: 1.825, loss: 0.316848
epoch 15, w: 1.851, loss: 0.228923
epoch 16, w: 1.874, loss: 0.165397
epoch 17, w: 1.893, loss: 0.119499
epoch 18, w: 1.909, loss: 0.086338
epoch 19, w: 1.922, loss: 0.062379
epoch 20, w: 1.934, loss: 0.045069
epoch 21, w: 1.944, loss: 0.032562
epoch 22, w: 1.952, loss: 0.023526
epoch 23, w: 1.960, loss: 0.016998
epoch 24, w: 1.966, loss: 0.012281
epoch 25, w: 1.971, loss: 0.008873
epoch 26, w: 1.975, loss: 0.006411
epoch 27, w: 1.979, loss: 

### Type 2: Use PyTorch Neural Networks Module for model training

In [18]:
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

n_samples, n_features = X.shape

print(X, X.shape)
print(y)

tensor([[1.],
        [2.],
        [3.],
        [4.]]) torch.Size([4, 1])
tensor([[2.],
        [4.],
        [6.],
        [8.]])


In [19]:
X_test = torch.tensor([5], dtype=torch.float32)
print(X_test, X_test.shape)

tensor([5.]) torch.Size([1])


In [20]:
input_size, output_size = n_features, n_features
model = nn.Linear(input_size, output_size)

In [21]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
alpha = 0.01
iterations = 100
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=alpha)
print(w, alpha, iterations)
print(loss, optimizer)

tensor(0., requires_grad=True) 0.01 100
MSELoss() SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [22]:
print(model(X_test).item())

for epoch in range(iterations):
    # predict
    y_pred = model(X)

    # calculate loss
    l = loss(y, y_pred)

    # gradient descent => backward pass in pytorch
    l.backward()

    # update weights
    optimizer.step()

    [w, b] = model.parameters()
    print(f"epoch {epoch}, w: {w[0][0].item():.3f}, loss: {l:5f}")

print(model(X_test).item())

3.4587202072143555
epoch 0, w: 1.020, loss: 14.510107
epoch 1, w: 1.401, loss: 10.069775
epoch 2, w: 1.893, loss: 4.031501
epoch 3, w: 2.411, loss: 0.260543
epoch 4, w: 2.871, loss: 1.170763
epoch 5, w: 3.194, loss: 6.179425
epoch 6, w: 3.327, loss: 12.080225
epoch 7, w: 3.247, loss: 15.095757
epoch 8, w: 2.968, loss: 13.295565
epoch 9, w: 2.536, loss: 7.831866
epoch 10, w: 2.022, loss: 2.202020
epoch 11, w: 1.512, loss: 0.009722
epoch 12, w: 1.091, loss: 2.658171
epoch 13, w: 0.830, loss: 8.451839
epoch 14, w: 0.770, loss: 13.681831
epoch 15, w: 0.923, loss: 15.000084
epoch 16, w: 1.261, loss: 11.562565
epoch 17, w: 1.728, loss: 5.569572
epoch 18, w: 2.246, loss: 0.857254
epoch 19, w: 2.728, loss: 0.441964
epoch 20, w: 3.092, loss: 4.589386
epoch 21, w: 3.277, loss: 10.644478
epoch 22, w: 3.253, loss: 14.731043
epoch 23, w: 3.022, loss: 14.233019
epoch 24, w: 2.622, loss: 9.469100
epoch 25, w: 2.121, loss: 3.488750
epoch 26, w: 1.600, loss: 0.120121
epoch 27, w: 1.147, loss: 1.519531
