In [7]:
import torch
import torchvision
from torch.utils.data import DataLoader, Dataset
import numpy as np
import math

In [8]:
class WineDataset(Dataset):
    def __init__(self):
        # data loading
        xy = np.loadtxt('./data/wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[:, [0]])  # n_samples, 1
        self.n_samples = xy.shape[0]

    def __getitem__(self, item):
        # indexing
        return self.x[item], self.y[item]

    def __len__(self):
        # length
        return self.n_samples

In [9]:
dataset = WineDataset()

In [10]:
first_data = dataset[0]
features, labels = first_data
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [11]:
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=0)

In [12]:
dataiter = iter(dataloader)
print(dataiter)

In [13]:
data = next(dataiter)
print(data)

[tensor([[1.3720e+01, 1.4300e+00, 2.5000e+00, 1.6700e+01, 1.0800e+02, 3.4000e+00,
         3.6700e+00, 1.9000e-01, 2.0400e+00, 6.8000e+00, 8.9000e-01, 2.8700e+00,
         1.2850e+03],
        [1.2690e+01, 1.5300e+00, 2.2600e+00, 2.0700e+01, 8.0000e+01, 1.3800e+00,
         1.4600e+00, 5.8000e-01, 1.6200e+00, 3.0500e+00, 9.6000e-01, 2.0600e+00,
         4.9500e+02],
        [1.2370e+01, 1.2100e+00, 2.5600e+00, 1.8100e+01, 9.8000e+01, 2.4200e+00,
         2.6500e+00, 3.7000e-01, 2.0800e+00, 4.6000e+00, 1.1900e+00, 2.3000e+00,
         6.7800e+02],
        [1.4830e+01, 1.6400e+00, 2.1700e+00, 1.4000e+01, 9.7000e+01, 2.8000e+00,
         2.9800e+00, 2.9000e-01, 1.9800e+00, 5.2000e+00, 1.0800e+00, 2.8500e+00,
         1.0450e+03]]), tensor([[1.],
        [2.],
        [2.],
        [1.]])]


In [14]:
features, labels = data
print(features, labels)

tensor([[1.3720e+01, 1.4300e+00, 2.5000e+00, 1.6700e+01, 1.0800e+02, 3.4000e+00,
         3.6700e+00, 1.9000e-01, 2.0400e+00, 6.8000e+00, 8.9000e-01, 2.8700e+00,
         1.2850e+03],
        [1.2690e+01, 1.5300e+00, 2.2600e+00, 2.0700e+01, 8.0000e+01, 1.3800e+00,
         1.4600e+00, 5.8000e-01, 1.6200e+00, 3.0500e+00, 9.6000e-01, 2.0600e+00,
         4.9500e+02],
        [1.2370e+01, 1.2100e+00, 2.5600e+00, 1.8100e+01, 9.8000e+01, 2.4200e+00,
         2.6500e+00, 3.7000e-01, 2.0800e+00, 4.6000e+00, 1.1900e+00, 2.3000e+00,
         6.7800e+02],
        [1.4830e+01, 1.6400e+00, 2.1700e+00, 1.4000e+01, 9.7000e+01, 2.8000e+00,
         2.9800e+00, 2.9000e-01, 1.9800e+00, 5.2000e+00, 1.0800e+00, 2.8500e+00,
         1.0450e+03]]) tensor([[1.],
        [2.],
        [2.],
        [1.]])


In [15]:
n_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
print(n_epochs, total_samples, n_iterations)

2 178 45


In [16]:
for epoch in range(n_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        if i % 5 == 0:
            print(f"epoch {epoch+1}/{n_epochs}, step {i+1}/{n_iterations}, inputs {inputs.shape}")

epoch 1/2, step 1/45, inputs torch.Size([4, 13])
epoch 1/2, step 6/45, inputs torch.Size([4, 13])
epoch 1/2, step 11/45, inputs torch.Size([4, 13])
epoch 1/2, step 16/45, inputs torch.Size([4, 13])
epoch 1/2, step 21/45, inputs torch.Size([4, 13])
epoch 1/2, step 26/45, inputs torch.Size([4, 13])
epoch 1/2, step 31/45, inputs torch.Size([4, 13])
epoch 1/2, step 36/45, inputs torch.Size([4, 13])
epoch 1/2, step 41/45, inputs torch.Size([4, 13])
epoch 2/2, step 1/45, inputs torch.Size([4, 13])
epoch 2/2, step 6/45, inputs torch.Size([4, 13])
epoch 2/2, step 11/45, inputs torch.Size([4, 13])
epoch 2/2, step 16/45, inputs torch.Size([4, 13])
epoch 2/2, step 21/45, inputs torch.Size([4, 13])
epoch 2/2, step 26/45, inputs torch.Size([4, 13])
epoch 2/2, step 31/45, inputs torch.Size([4, 13])
epoch 2/2, step 36/45, inputs torch.Size([4, 13])
epoch 2/2, step 41/45, inputs torch.Size([4, 13])


In [17]:
class WineDatasetNew(Dataset):
    def __init__(self, transform=None):
        # data loading
        xy = np.loadtxt('./data/wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.x = xy[:, 1:]
        self.y = xy[:, [0]]  # n_samples, 1
        self.n_samples = xy.shape[0]

        self.transform = transform

    def __getitem__(self, item):
        # indexing
        sample = self.x[item], self.y[item]
        if self.transform:
            sample = self.transform(sample)
        return sample

    def __len__(self):
        # length
        return self.n_samples

In [18]:
class ToTensor:
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [22]:
class MultTransform:
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        return inputs, targets

In [19]:
dataset_new = WineDatasetNew(transform=ToTensor())

In [23]:
first = dataset_new[0]
print(first)
features, labels = first
print(features)
print(labels)

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]), tensor([1.]))
tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor([1.])


In [24]:
composed = torchvision.transforms.Compose([ToTensor(), MultTransform(2)])
ds = WineDatasetNew(transform=composed)

In [25]:
first = ds[0]
print(first)
features, labels = first
print(features)
print(labels)

(tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03]), tensor([1.]))
tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03])
tensor([1.])
