In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.5283, -0.0507, -0.7784], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([2.5283, 1.9493, 1.2216], grad_fn=<AddBackward0>)


In [4]:
z = y * y * 2
print(z)

tensor([12.7849,  7.5997,  2.9847], grad_fn=<MulBackward0>)


In [5]:
z = z.mean()
print(z)

tensor(7.7898, grad_fn=<MeanBackward0>)


In [6]:
z.backward()
print(x.grad)

tensor([3.3711, 2.5991, 1.6288])


In [14]:
z1 = y * y * 2
print(z1)

tensor([12.7849,  7.5997,  2.9847], grad_fn=<MulBackward0>)


In [15]:
z1.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [16]:
v = torch.tensor([1, 0.1, 0.01], dtype=torch.float32)
print(v)

tensor([1.0000, 0.1000, 0.0100])


In [18]:
z1.backward(v)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [19]:
print(x.grad)

tensor([16.7143,  3.1864,  0.9877])


In [20]:
print(x)
x.requires_grad_(False)
print(x)

tensor([ 0.5283, -0.0507, -0.7784], requires_grad=True)
tensor([ 0.5283, -0.0507, -0.7784])


In [21]:
x.requires_grad_(True)
print(x)
y = x.detach()
print(y)

tensor([ 0.5283, -0.0507, -0.7784], requires_grad=True)
tensor([ 0.5283, -0.0507, -0.7784])


In [22]:
with torch.no_grad():
    y = x + 2
    print(x)
    print(y)

tensor([ 0.5283, -0.0507, -0.7784], requires_grad=True)
tensor([2.5283, 1.9493, 1.2216])


In [23]:
weights = torch.ones(4, requires_grad=True)
print(weights)

tensor([1., 1., 1., 1.], requires_grad=True)


In [24]:
for _ in range(3):
    model_output = (weights*5).sum()
    model_output.backward()
    print(weights.grad)

tensor([5., 5., 5., 5.])
tensor([10., 10., 10., 10.])
tensor([15., 15., 15., 15.])


In [26]:
for _ in range(3):
    model_output = (weights*5).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    print(weights.grad)


tensor([5., 5., 5., 5.])
tensor([0., 0., 0., 0.])
tensor([5., 5., 5., 5.])
tensor([0., 0., 0., 0.])
tensor([5., 5., 5., 5.])
tensor([0., 0., 0., 0.])


### Backpropagation

In [27]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
print(x)
print(y)

tensor(1.)
tensor(2.)


In [28]:
w = torch.tensor(1.0, requires_grad=True)
print(w)

tensor(1., requires_grad=True)


In [29]:
y_hat = w * x
loss = (y_hat - y) ** 2
print(y_hat)
print(loss)

tensor(1., grad_fn=<MulBackward0>)
tensor(1., grad_fn=<PowBackward0>)


In [30]:
loss.backward()

In [31]:
print(w.grad)

tensor(-2.)
