In [1]:
import torch
import numpy as np

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1022, 0.5405, 0.9857],
        [0.4109, 0.4598, 0.9693],
        [0.9723, 0.6975, 0.3840],
        [0.9243, 0.1394, 0.4207],
        [0.2379, 0.0600, 0.3655]])


In [3]:
torch.cuda.is_available()

True

In [4]:
x = torch.empty(2)
print(x)
x = torch.empty(2, 2)
print(x, x.dtype)
x = torch.empty(2, dtype=int)
print(x)
x = torch.empty(2, 2, dtype=int)
print(x)

tensor([0., 0.])
tensor([[0., 0.],
        [0., 0.]]) torch.float32
tensor([0, 0])
tensor([[0, 0],
        [0, 0]])


In [5]:
y = torch.zeros(2)
print(y)
y = torch.ones(2)
print(y)

tensor([0., 0.])
tensor([1., 1.])


In [6]:
z = torch.tensor([2.5, 6.9])
print(z, z.dtype)
z = torch.tensor([2.5, 6.9], dtype=float)
print(z, z.dtype)

tensor([2.5000, 6.9000]) torch.float32
tensor([2.5000, 6.9000], dtype=torch.float64) torch.float64


In [7]:
x = torch.rand(2, 2)
print(x)
y = torch.rand(2, 2)
print(y)

tensor([[0.5130, 0.1124],
        [0.9661, 0.5520]])
tensor([[0.5741, 0.0122],
        [0.6056, 0.4659]])


In [8]:
z1 = x + y
print(z1)
z2 = torch.add(x, y)
print(z2)
x.add_(y)
print(x)

tensor([[1.0871, 0.1246],
        [1.5717, 1.0178]])
tensor([[1.0871, 0.1246],
        [1.5717, 1.0178]])
tensor([[1.0871, 0.1246],
        [1.5717, 1.0178]])


In [9]:
z1 = x - y
print(z1)
z2 = torch.sub(x, y)
print(z2)
y.sub_(x)
print(y)

tensor([[0.5130, 0.1124],
        [0.9661, 0.5520]])
tensor([[0.5130, 0.1124],
        [0.9661, 0.5520]])
tensor([[-0.5130, -0.1124],
        [-0.9661, -0.5520]])


In [10]:
z1 = x * y
print(z1)
z2 = torch.mul(x, y)
print(z2)
y.mul_(x)
print(y)

tensor([[-0.5577, -0.0140],
        [-1.5183, -0.5618]])
tensor([[-0.5577, -0.0140],
        [-1.5183, -0.5618]])
tensor([[-0.5577, -0.0140],
        [-1.5183, -0.5618]])


In [11]:
z1 = x / y
print(z1)
z2 = torch.div(x, y)
print(z2)
x.div_(y)
print(x)

tensor([[-1.9493, -8.8983],
        [-1.0351, -1.8116]])
tensor([[-1.9493, -8.8983],
        [-1.0351, -1.8116]])
tensor([[-1.9493, -8.8983],
        [-1.0351, -1.8116]])


In [12]:
x = torch.rand(4, 4)
print(x)
print(x[:, 0])
print(x[0, :])
print(x[0, 0])

tensor([[0.3803, 0.9789, 0.9010, 0.0116],
        [0.0244, 0.6660, 0.4278, 0.1352],
        [0.4696, 0.4361, 0.1551, 0.9946],
        [0.8289, 0.5360, 0.4539, 0.5649]])
tensor([0.3803, 0.0244, 0.4696, 0.8289])
tensor([0.3803, 0.9789, 0.9010, 0.0116])
tensor(0.3803)


In [13]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)
y = x.view(-1, 2)
print(y)
y = x.view(2, -1)
print(y)

tensor([[0.4736, 0.2728, 0.4895, 0.1095],
        [0.1224, 0.2961, 0.1578, 0.0705],
        [0.1494, 0.4141, 0.0016, 0.2814],
        [0.5937, 0.4312, 0.7651, 0.7889]])
tensor([0.4736, 0.2728, 0.4895, 0.1095, 0.1224, 0.2961, 0.1578, 0.0705, 0.1494,
        0.4141, 0.0016, 0.2814, 0.5937, 0.4312, 0.7651, 0.7889])
tensor([[0.4736, 0.2728],
        [0.4895, 0.1095],
        [0.1224, 0.2961],
        [0.1578, 0.0705],
        [0.1494, 0.4141],
        [0.0016, 0.2814],
        [0.5937, 0.4312],
        [0.7651, 0.7889]])
tensor([[0.4736, 0.2728, 0.4895, 0.1095, 0.1224, 0.2961, 0.1578, 0.0705],
        [0.1494, 0.4141, 0.0016, 0.2814, 0.5937, 0.4312, 0.7651, 0.7889]])


In [14]:
# pytorch <-> numpy
x = torch.rand(3, 3)
print(x, type(x))
y = x.numpy()
print(y, type(y))

x = np.random.rand(3, 3)
print(x, type(x))
y = torch.from_numpy(x)
print(y, type(y))

tensor([[0.7435, 0.8872, 0.7082],
        [0.4440, 0.0228, 0.1395],
        [0.9224, 0.2723, 0.8452]]) <class 'torch.Tensor'>
[[0.74350286 0.8871811  0.7081824 ]
 [0.44399166 0.02278399 0.13952792]
 [0.92239195 0.27228963 0.8451501 ]] <class 'numpy.ndarray'>
[[0.9467361  0.90773346 0.40306551]
 [0.94778092 0.36118365 0.75572446]
 [0.16647744 0.61264263 0.79721658]] <class 'numpy.ndarray'>
tensor([[0.9467, 0.9077, 0.4031],
        [0.9478, 0.3612, 0.7557],
        [0.1665, 0.6126, 0.7972]], dtype=torch.float64) <class 'torch.Tensor'>


In [15]:
x = torch.rand(2, 2)
print(x)
y = x.numpy()
print(y)
y += 1
print(x)
print(y)

tensor([[0.9128, 0.8228],
        [0.1792, 0.1705]])
[[0.9128033  0.82282674]
 [0.17923832 0.17051488]]
tensor([[1.9128, 1.8228],
        [1.1792, 1.1705]])
[[1.9128033 1.8228267]
 [1.1792383 1.1705148]]


In [16]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(2, 2, device=device)
    print(x)
    y = torch.ones(2, 2)
    y = y.to(device)
    print(y)

    z = x + y
    print(z)
    # z.numpy()
    # print(z)
    z = z.to("cpu")
    z = z.numpy()
    print(z)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[2., 2.],
        [2., 2.]], device='cuda:0')
[[2. 2.]
 [2. 2.]]


In [17]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
